package com.example.booknotes

object Constant {

    const val SHARED_PREFERENCES_NAME = "BOOK_NOTES_SHARED_PREF"
    const val SHARED_KEY_DATE_CREATED = "SORTING_DATE_CREATED"
    const val SHARED_KEY_PAGE_NUMBER = "SORTING_PAGE_NUMBER"
    const val SHARED_KEY_FILTERING_FAVORITE = "FILTERING_FAVORITE"
}